data:
  raw_path: r"C:\Guvi\NutriClass Food Classification Using Nutritional Data\data\raw\synthetic_food_dataset_imbalanced.csv"
  processed_path: "data/processed/food_data_final.csv"

model:
  save_path: "models/random_forest.pkl"

features:
  - Calories
  - Proteins
  - Carbs
  - Fats
  - Sugar

target: "FoodCategory"
